fix shellcheck issues, improve help, add -V

diff --git a/clonelocalgit b/clonelocalgit
--- a/clonelocalgit
+++ b/clonelocalgit
@@ -1,8 +1,8 @@
-#!/bin/bash -
+#!/usr/bin/env bash
 #
 # clonelocalgit - clone a git repo from a local repo
 #
-# Copyright (c) 2016,2021 by Landon Curt Noll.  All Rights Reserved.
+# Copyright (c) 2016,2021,2025 by Landon Curt Noll.  All Rights Reserved.
 #
 # Permission to use, copy, modify, and distribute this software and
 # its documentation for any purpose and without fee is hereby granted,
@@ -22,30 +22,41 @@
 # OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
 # PERFORMANCE OF THIS SOFTWARE.
 #
-# chongo (Landon Curt Noll, http://www.isthe.com/chongo/index.html) /\oo/\
+# chongo (Landon Curt Noll) /\oo/\
 #
-# Share and enjoy! :-)
+# http://www.isthe.com/chongo/index.html
+# https://github.com/lcn2
+#
+# Share and enjoy!
+
 
 # setup
 #
+export VERSION="1.0.0 2025-03-17"
 export LOC_REPO_TREE="/usr/local/git"
-export USAGE="usage: $0 [-h] [-n] [-v] [-r repotree] repo_name parent_dir
-
-	-h            print this message and exit
-
-	-r repotree   tree on hostname containing reponame.git (def: $LOC_REPO_TREE)
-
-        -n            do not create anything
-	-v            be verbose
-
-	repo_name    name of the git repo under repotree (without the .git)
-	parent_dir   clone the git repo under parent_dir/repo_name"
 export VERBOSE=""
 export NO_OP=""
+NAME=$(basename "$0")
+export NAME
+#
+export USAGE="usage: $NAME [-h] [-v] [-V] [-n] [-r repotree] repo_name parent_dir
+
+    -h            print this message and exit
+    -v            be verbose
+    -V            print version string and exit
+
+    -n            do not create anything
+
+    -r repotree   tree on hostname containing reponame.git (def: $LOC_REPO_TREE)
+
+    repo_name     name of the git repo under repotree (without the .git)
+    parent_dir    clone the git repo under parent_dir/repo_name
+
+$NAME version: $VERSION"
 
 # parse args
 #
-while getopts :hr:nv flag; do
+while getopts :hr:nvV flag; do
     case "$flag" in
     h) echo "$USAGE" 1>&2;
        exit 0
@@ -56,10 +67,24 @@ while getopts :hr:nv flag; do
        ;;
     v) VERBOSE="-v"
        ;;
-    ?) echo "$0: FATAL: unknown or invalid -flag" 1>&2 ;
-       echo "$USAGE" 1>&2 ;
-       exit 1
+    V) echo "$VERSION"
+	exit 2
        ;;
+    \?) echo "$0: ERROR: invalid option: -$OPTARG" 1>&2
+        echo 1>&2
+        echo "$USAGE" 1>&2
+        exit 3
+        ;;
+    :) echo "$0: ERROR: option -$OPTARG requires an argument" 1>&2
+        echo 1>&2
+        echo "$USAGE" 1>&2
+        exit 3
+        ;;
+    *) echo "$0: ERROR: unexpected value from getopts: $flag" 1>&2
+        echo 1>&2
+        echo "$USAGE" 1>&2
+        exit 3
+        ;;
     esac
 done
 shift $(( OPTIND - 1 ));
@@ -74,12 +99,12 @@ export PARENT_DIR="$2"
 # firewall
 #
 if [[ ! -d "$PARENT_DIR" ]]; then
-    echo "$0: FATAL: not a directory: $DIR" 1>&2
-    exit 3
+    echo "$0: FATAL: not a directory: $PARENT_DIR" 1>&2
+    exit 4
 fi
 if [[ -e "$PARENT_DIR/$REPO_NAME" ]]; then
     echo "$0: FATAL: directory exists: $PARENT_DIR/$REPO_NAME" 1>&2
-    exit 4
+    exit 5
 fi
 
 # determine if readlink --canonicalize-existing works
@@ -100,16 +125,16 @@ if [[ -n $HAS_CANONICALIZE_EXISTING ]]; then
     status="$?"
     if [[ "$status" -ne 0 ]]; then
 	echo "$0: FATAL: cannot canonicalize $PARENT_DIR, error code: $status" 1>&2
-	exit 5
-    fi
-    if [[ -z "$CANON_DIR" ]]; then
-	echo "$0: FATAL: DIR canonicalized $DIR to empty string" 1>&2
 	exit 6
     fi
+    if [[ -z "$CANON_DIR" ]]; then
+	echo "$0: FATAL: DIR canonicalized $CANON_DIR to empty string" 1>&2
+	exit 7
+    fi
 else
-    CANON_DIR=$(perl -MCwd -e 'print Cwd::realpath($ARGV[0]), "\n"' "$DIR")
+    CANON_DIR=$(perl -MCwd -e 'print Cwd::realpath($ARGV[0]), "\n"' "$CANON_DIR")
 fi
-if [[ -n "$VERBOSE" ]]; then
+if [[ -n $VERBOSE ]]; then
     echo "$0: Notice: CANON_DIR: $CANON_DIR" 1>&2
 fi
 
@@ -118,11 +143,14 @@ fi
 if [[ -n "$VERBOSE" ]]; then
    echo "$0: Notice: cd $CANON_DIR" 1>&2
 fi
-cd "$CANON_DIR"
-status="$?"
-if [[ "$status" -ne 0 ]]; then
-    echo "$0: FATAL: cannot cd $CANON_DIR, error code: $status" 1>&2
-    exit 7
+export CD_FAILED=""
+cd "$CANON_DIR" || CD_FAILED="true"
+if [[ -n $CD_FAILED ]]; then
+    echo "$0: ERROR: cd $CANON_DIR failed" 1>&2
+    exit 8
+fi
+if [[ -n $VERBOSE ]]; then
+    echo "$0: debug[3]: now in directory: $(/bin/pwd)" 1>&2
 fi
 
 # determine if $LOC_REPO_TREE is same filesystem as $CANON_DIR
@@ -150,19 +178,19 @@ if [[ -z "$NO_OP" ]]; then
 	status="$?"
 	if [[ "$status" -ne 0 ]]; then
 	    echo "$0: FATAL: git clone error: $status" 1>&2
-	    exit 8
+	    exit 9
 	fi
     else
 	git clone --local "$CLONE_ARG" "$LOC_REPO_TREE/$REPO_NAME"
 	status="$?"
 	if [[ "$status" -ne 0 ]]; then
 	    echo "$0: FATAL: git clone error: $status" 1>&2
-	    exit 9
+	    exit 10
 	fi
     fi
     if [[ ! -d "$CANON_DIR/$REPO_NAME" ]]; then
 	echo "$0: FATAL: clone did not form directory: $CANON_DIR/$REPO_NAME" 1>&2
-	exit 10
+	exit 11
     fi
 fi
 
@@ -172,11 +200,14 @@ if [[ -z "$NO_OP" ]]; then
     if [[ -n "$VERBOSE" ]]; then
        echo "$0: Notice: cd $CANON_DIR/$REPO_NAME" 1>&2
     fi
-    cd "$CANON_DIR/$REPO_NAME"
-    status="$?"
-    if [[ "$status" -ne 0 ]]; then
-	echo "$0: FATAL: cannot cd $CANON_DIR/$REPO_NAME, error code: $status" 1>&2
-	exit 11
+    export CD_FAILED=""
+    cd "$CANON_DIR/$REPO_NAME" || CD_FAILED="true"
+    if [[ -n $CD_FAILED ]]; then
+	echo "$0: ERROR: cd $CANON_DIR failed" 1>&2
+	exit 12
+    fi
+    if [[ -n $VERBOSE ]]; then
+	echo "$0: debug[3]: now in directory: $(/bin/pwd)" 1>&2
     fi
 fi
 
@@ -188,7 +219,7 @@ if [[ -n "$VERBOSE" && -z "$NO_OP" ]]; then
     status="$?"
     if [[ "$status" -ne 0 ]]; then
 	echo "$0: FATAL: git remote error: $status" 1>&2
-	exit 12
+	exit 13
     fi
 fi
 
diff --git a/ghreplace b/ghreplace
--- a/ghreplace
+++ b/ghreplace
@@ -4,7 +4,7 @@
 #
 # Replace a local src tree with GitHub repo content, remove local git repo
 #
-# Copyright (c) 2023 by Landon Curt Noll.  All Rights Reserved.
+# Copyright (c) 2023,2025 by Landon Curt Noll.  All Rights Reserved.
 #
 # Permission to use, copy, modify, and distribute this software and
 # its documentation for any purpose and without fee is hereby granted,
@@ -24,12 +24,17 @@
 # OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
 # PERFORMANCE OF THIS SOFTWARE.
 #
-# chongo (Landon Curt Noll, http://www.isthe.com/chongo/index.html) /\oo/\
+# chongo (Landon Curt Noll) /\oo/\
 #
-# Share and enjoy! :-)
+# http://www.isthe.com/chongo/index.html
+# https://github.com/lcn2
+#
+# Share and enjoy!
+
 
 # setup
 #
+export VERSION="1.0.0 2025-03-17"
 export GITHUB_USER="lcn2"
 export LOCAL_SRC_TREE="/usr/local/src/bin"
 export LOCAL_GIT_TREE="/usr/local/git"
@@ -37,11 +42,16 @@ export GITHUB_REPO_BASE="git@github.com:$GITHUB_USER"
 export GITHUB_USER_URL="https://github.com/$GITHUB_USER"
 export N_FLAG=
 export V_FLAG=
-export USAGE="usage: $0 [-h] [-n] [-v] [-g gittree] [-s srctop] [-u user] dirname
+NAME=$(basename "$0")
+export NAME
+#
+export USAGE="usage: $NAME [-h] [-v] [-V] [-n] [-g gittree] [-s srctop] [-u user] dirname
 
     -h		print help and exit
-    -n		do not change anything
     -v		be verbose
+    -V          print version string and exit
+
+    -n		do not change anything
 
     -s srctop	path to top of source above name (def: $LOCAL_SRC_TREE)
     -g gittree	path to local git tree (def: $LOCAL_GIT_TREE)
@@ -56,16 +66,22 @@ Exit codes:
     1	operation failed
     2	print help and exit
     3	command line error
- >=10	internal error"
+ >=10	internal error
+
+$NAME version: $VERSION"
+
 
 # parse args
 #
-while getopts :hnvg:s:u: flag; do
+while getopts :hnvVg:s:u: flag; do
     case "$flag" in
     h) echo "$USAGE"
        exit 2
        ;;
     v) V_FLAG="-v"
+       ;;
+    V) echo "$VERSION"
+	exit 2
        ;;
     n) N_FLAG="-n"
        ;;
@@ -77,14 +93,21 @@ while getopts :hnvg:s:u: flag; do
        GITHUB_REPO_BASE="git@github.com:$GITHUB_USER"
        GITHUB_USER_URL="https://github.com/$GITHUB_USER"
        ;;
-    \?) echo "invalid option: -$OPTARG" 1>&2
-	echo "$USAGE" 1>&2
+    \?) echo "$0: ERROR: invalid option: -$OPTARG" 1>&2
+        echo 1>&2
+        echo "$USAGE" 1>&2
         exit 3
-	;;
-    :)  echo "option -$OPTARG requires an argument" 1>&2
-	echo "$USAGE" 1>&2
-	exit 3
-	;;
+        ;;
+    :) echo "$0: ERROR: option -$OPTARG requires an argument" 1>&2
+        echo 1>&2
+        echo "$USAGE" 1>&2
+        exit 3
+        ;;
+    *) echo "$0: ERROR: unexpected value from getopts: $flag" 1>&2
+        echo 1>&2
+        echo "$USAGE" 1>&2
+        exit 3
+        ;;
     esac
 done
 shift $(( OPTIND - 1 ));
diff --git a/mkgitrepo b/mkgitrepo
--- a/mkgitrepo
+++ b/mkgitrepo
@@ -1,8 +1,8 @@
-#!/bin/bash -
+#!/usr/bin/env bash
 #
 # mkgitrepo - make remote bare repo on localhost from from a dir under git
 #
-# Copyright (c) 2016,2021 by Landon Curt Noll.  All Rights Reserved.
+# Copyright (c) 2016,2021,2025 by Landon Curt Noll.  All Rights Reserved.
 #
 # Permission to use, copy, modify, and distribute this software and
 # its documentation for any purpose and without fee is hereby granted,
@@ -22,29 +22,40 @@
 # OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
 # PERFORMANCE OF THIS SOFTWARE.
 #
-# chongo (Landon Curt Noll, http://www.isthe.com/chongo/index.html) /\oo/\
+# chongo (Landon Curt Noll) /\oo/\
 #
-# Share and enjoy! :-)
+# http://www.isthe.com/chongo/index.html
+# https://github.com/lcn2
+#
+# Share and enjoy!
+
 
 # setup
 #
+export VERSION="1.0.0 2025-03-17"
 export LOC_REPO_DIR="/usr/local/git"
-export USAGE="usage: $0 [-h] [-r locrepo] [-n] [-v] dir
-
-	-h          print this message and exit
-
-	-r locrepo  directory of the local git repo (def: $LOC_REPO_DIR)
-
-        -n          do not create anything
-	-v          be verbose
-
-	dir	    directory that bare repo under $LOC_REPO_DIR is cloned from"
 export VERBOSE=""
 export NO_OP=""
+NAME=$(basename "$0")
+export NAME
+#
+export USAGE="usage: $NAME [-h] [-v] [-V] [-n] [-r locrepo] dir
+
+    -h          print this message and exit
+    -v          be verbose
+    -V          print version string and exit
+
+    -n          do not create anything
+
+    -r locrepo  directory of the local git repo (def: $LOC_REPO_DIR)
+
+    dir	    directory that bare repo under $LOC_REPO_DIR is cloned from
+
+$NAME version: $VERSION"
 
 # parse args
 #
-while getopts :hr:nv flag; do
+while getopts :hr:nvV flag; do
     case "$flag" in
     h) echo "$USAGE" 1>&2;
        exit 0
@@ -55,10 +66,24 @@ while getopts :hr:nv flag; do
        ;;
     v) VERBOSE="-v"
        ;;
-    ?) echo "$0: FATAL: unknown or invalid -flag" 1>&2 ;
-       echo "$USAGE" 1>&2 ;
-       exit 1
+    V) echo "$VERSION"
+	exit 2
        ;;
+    \?) echo "$0: ERROR: invalid option: -$OPTARG" 1>&2
+        echo 1>&2
+        echo "$USAGE" 1>&2
+        exit 3
+        ;;
+    :) echo "$0: ERROR: option -$OPTARG requires an argument" 1>&2
+        echo 1>&2
+        echo "$USAGE" 1>&2
+        exit 3
+        ;;
+    *) echo "$0: ERROR: unexpected value from getopts: $flag" 1>&2
+        echo 1>&2
+        echo "$USAGE" 1>&2
+        exit 3
+        ;;
     esac
 done
 shift $(( OPTIND - 1 ));
@@ -73,19 +98,19 @@ export DIR="$1"
 #
 if [[ ! -e "$DIR" ]]; then
     echo "$0: FATAL: directory does not exist: $DIR" 1>&2
-    exit 3
+    exit 4
 fi
 if [[ ! -d "$DIR" ]]; then
     echo "$0: FATAL: not a directory: $DIR" 1>&2
-    exit 4
+    exit 5
 fi
 if [[ ! -e "$LOC_REPO_DIR" ]]; then
     echo "$0: FATAL: repo directory does not exist: $LOC_REPO_DIR" 1>&2
-    exit 5
+    exit 6
 fi
 if [[ ! -d "$LOC_REPO_DIR" ]]; then
     echo "$0: FATAL: repo is not a directory: $LOC_REPO_DIR" 1>&2
-    exit 6
+    exit 7
 fi
 
 # determine if readlink --canonicalize-existing works
@@ -106,11 +131,11 @@ if [[ -n $HAS_CANONICALIZE_EXISTING ]]; then
     status="$?"
     if [[ "$status" -ne 0 ]]; then
 	echo "$0: FATAL: cannot canonicalize $DIR, error code: $status" 1>&2
-	exit 7
+	exit 8
     fi
     if [[ -z "$CANON_DIR" ]]; then
 	echo "$0: FATAL: DIR canonicalized $DIR to empty string" 1>&2
-	exit 8
+	exit 9
     fi
 else
     CANON_DIR=$(perl -MCwd -e 'print Cwd::realpath($ARGV[0]), "\n"' "$DIR")
@@ -119,31 +144,35 @@ if [[ -n "$VERBOSE" ]]; then
     echo "$0: Notice: CANON_DIR: $CANON_DIR" 1>&2
 fi
 
-# move to the directory
+# move to the parent directory
 #
 if [[ -n "$VERBOSE" ]]; then
    echo "$0: Notice: cd $CANON_DIR" 1>&2
 fi
-cd "$CANON_DIR"
-status="$?"
-if [[ "$status" -ne 0 ]]; then
-    echo "$0: FATAL: cannot cd $CANON_DIR, error code: $status" 1>&2
-    exit 9
+export CD_FAILED=""
+cd "$CANON_DIR" || CD_FAILED="true"
+if [[ -n $CD_FAILED ]]; then
+    echo "$0: ERROR: cd $CANON_DIR failed" 1>&2
+    exit 10
+fi
+if [[ -n $VERBOSE ]]; then
+    echo "$0: debug[3]: now in directory: $(/bin/pwd)" 1>&2
 fi
 
 # reject if there is a similarly named git repo under $LOC_REPO_DIR
 #
-export NAME=$(basename "$CANON_DIR")
+REPO_NAME=$(basename "$CANON_DIR")
+export REPO_NAME
 if [[ -n "$VERBOSE" ]]; then
-    echo "$0: Notice: NAME: $NAME" 1>&2
+    echo "$0: Notice: REPO_NAME: $REPO_NAME" 1>&2
 fi
-if [[ -e "$LOC_REPO_DIR/$NAME" ]]; then
-    echo "$0: FATAL: similarly named git repo found under: $LOC_REPO_DIR/$NAME" 1>&2
-    exit 10
-fi
-if [[ -e "$LOC_REPO_DIR/$NAME.git" ]]; then
-    echo "$0: FATAL: similarly named git repo found under: $LOC_REPO_DIR/$NAME.git" 1>&2
+if [[ -e "$LOC_REPO_DIR/$REPO_NAME" ]]; then
+    echo "$0: FATAL: similarly named git repo found under: $LOC_REPO_DIR/$REPO_NAME" 1>&2
     exit 11
+fi
+if [[ -e "$LOC_REPO_DIR/$REPO_NAME.git" ]]; then
+    echo "$0: FATAL: similarly named git repo found under: $LOC_REPO_DIR/$REPO_NAME.git" 1>&2
+    exit 12
 fi
 
 # reject if not under git control or a sub-directory is under git control
@@ -153,18 +182,19 @@ if ! git rev-parse --is-inside-work >/dev/null 2>&1; then
     exit 12
 fi
 
-# clone a bare repo under $LOC_REPO_DIR/$NAME.git
-#
-# cd to $LOC_REPO_DIR
+# move to the bare repo under $LOC_REPO_DIR/$REPO_NAME.git
 #
 if [[ -n "$VERBOSE" ]]; then
    echo "$0: Notice: cd $LOC_REPO_DIR" 1>&2
 fi
-cd "$LOC_REPO_DIR"
-status="$?"
-if [[ "$status" -ne 0 ]]; then
-    echo "$0: FATAL: cannot cd $LOC_REPO_DIR, error code: $status" 1>&2
-    exit 13
+export CD_FAILED=""
+cd "$LOC_REPO_DIR" || CD_FAILED="true"
+if [[ -n $CD_FAILED ]]; then
+    echo "$0: ERROR: cd $LOC_REPO_DIR failed" 1>&2
+    exit 8
+fi
+if [[ -n $VERBOSE ]]; then
+    echo "$0: debug[3]: now in directory: $(/bin/pwd)" 1>&2
 fi
 
 # determine if $LOC_REPO_DIR is same filesystem as $CANON_DIR
@@ -192,28 +222,31 @@ if [[ -z "$NO_OP" ]]; then
 	status="$?"
 	if [[ "$status" -ne 0 ]]; then
 	    echo "$0: FATAL: git clone error: $status" 1>&2
-	    exit 14
+	    exit 13
 	fi
     else
 	git clone --bare --local "$CLONE_ARG" "$CANON_DIR"
 	status="$?"
 	if [[ "$status" -ne 0 ]]; then
 	    echo "$0: FATAL: git clone error: $status" 1>&2
-	    exit 15
+	    exit 14
 	fi
     fi
 fi
 
-# cd back to the directory
+# move back to the parent directory
 #
 if [[ -n "$VERBOSE" ]]; then
    echo "$0: Notice: cd $CANON_DIR" 1>&2
 fi
-cd "$CANON_DIR"
-status="$?"
-if [[ "$status" -ne 0 ]]; then
-    echo "$0: FATAL: cannot cd $CANON_DIR, error code: $status" 1>&2
-    exit 16
+export CD_FAILED=""
+cd "$CANON_DIR" || CD_FAILED="true"
+if [[ -n $CD_FAILED ]]; then
+    echo "$0: ERROR: cd $CANON_DIR failed" 1>&2
+    exit 15
+fi
+if [[ -n $VERBOSE ]]; then
+    echo "$0: debug[3]: now in directory: $(/bin/pwd)" 1>&2
 fi
 
 # show any existing git remote
@@ -224,7 +257,7 @@ if [[ -n "$VERBOSE" && -z "$NO_OP" ]]; then
     status="$?"
     if [[ "$status" -ne 0 ]]; then
 	echo "$0: FATAL: git remote error: $status" 1>&2
-	exit 17
+	exit 15
     fi
 fi
 
@@ -238,7 +271,7 @@ if [[ -z "$NO_OP" ]]; then
     status="$?"
     if [[ "$status" -ne 0 ]]; then
 	echo "$0: FATAL: git remote error: $status" 1>&2
-	exit 18
+	exit 16
     fi
     GIT_REMOTE=$(git remote)
     if [[ -z "$GIT_REMOTE" ]]; then
@@ -269,7 +302,7 @@ if [[ -z "$NO_OP" ]]; then
 	    status="$?"
 	    if [[ "$status" -ne 0 ]]; then
 		echo "$0: FATAL: git remote remote origin error: $status" 1>&2
-		exit 19
+		exit 17
 	    fi
 	fi
     fi
@@ -280,18 +313,18 @@ fi
 # set git remote
 #
 if [[ -n "$VERBOSE" ]]; then
-    echo "$0: Notice: git remote -v add origin $LOC_REPO_DIR/$NAME" 1>&2
+    echo "$0: Notice: git remote -v add origin $LOC_REPO_DIR/$REPO_NAME" 1>&2
 fi
 if [[ -z "$NO_OP" ]]; then
     if [[ -n "$VERBOSE" ]]; then
-	git remote -v add origin "$LOC_REPO_DIR/$NAME"
+	git remote -v add origin "$LOC_REPO_DIR/$REPO_NAME"
     else
-	git remote add origin "$LOC_REPO_DIR/$NAME"
+	git remote add origin "$LOC_REPO_DIR/$REPO_NAME"
     fi
     status="$?"
     if [[ "$status" -ne 0 ]]; then
 	echo "$0: FATAL: git remote error: $status" 1>&2
-	exit 20
+	exit 18
     fi
 fi
 
@@ -309,7 +342,7 @@ if [[ -z "$NO_OP" ]]; then
     status="$?"
     if [[ "$status" -ne 0 ]]; then
 	echo "$0: FATAL: git fetch error: $status" 1>&2
-	exit 21
+	exit 19
     fi
 fi
 
@@ -321,7 +354,7 @@ if [[ -n "$VERBOSE" && -z "$NO_OP" ]]; then
     status="$?"
     if [[ "$status" -ne 0 ]]; then
 	echo "$0: FATAL: git remote error: $status" 1>&2
-	exit 22
+	exit 20
     fi
 fi
 
diff --git a/syncgit b/syncgit
--- a/syncgit
+++ b/syncgit
@@ -1,8 +1,8 @@
-#!/bin/bash -
+#!/usr/bin/env bash
 #
 # syncgit - rebase and sync changes with a git repository
 #
-# Copyright (c) 2016,2021 by Landon Curt Noll.  All Rights Reserved.
+# Copyright (c) 2016,2021,2025 by Landon Curt Noll.  All Rights Reserved.
 #
 # Permission to use, copy, modify, and distribute this software and
 # its documentation for any purpose and without fee is hereby granted,
@@ -28,20 +28,27 @@
 
 # setup
 #
-export USAGE="usage: $0 [-h] [-n] [-v] dir
-
-	-h          print this message and exit
-
-        -n          do not create anything
-	-v          be verbose
-
-	dir	    sync content of dir with the git repo"
+export VERSION="1.0.0 2025-03-17"
 export VERBOSE=""
 export NO_OP=""
+NAME=$(basename "$0")
+export NAME
+#
+export USAGE="usage: $NAME [-h] [-n] [-v] dir
+
+    -h          print this message and exit
+    -v          be verbose
+    -V          print version string and exit
+
+    -n          do not create anything
+
+    dir         sync content of dir with the git repo
+
+$NAME version: $VERSION"
 
 # parse args
 #
-while getopts :hnv flag; do
+while getopts :hnvV flag; do
     case "$flag" in
     h) echo "$USAGE" 1>&2;
        exit 0
@@ -50,10 +57,24 @@ while getopts :hnv flag; do
        ;;
     v) VERBOSE="-v"
        ;;
-    ?) echo "$0: FATAL: unknown or invalid -flag" 1>&2 ;
-       echo "$USAGE" 1>&2 ;
-       exit 1
+    V) echo "$VERSION"
+	exit 2
        ;;
+    \?) echo "$0: ERROR: invalid option: -$OPTARG" 1>&2
+        echo 1>&2
+        echo "$USAGE" 1>&2
+        exit 3
+        ;;
+    :) echo "$0: ERROR: option -$OPTARG requires an argument" 1>&2
+        echo 1>&2
+        echo "$USAGE" 1>&2
+        exit 3
+        ;;
+    *) echo "$0: ERROR: unexpected value from getopts: $flag" 1>&2
+        echo 1>&2
+        echo "$USAGE" 1>&2
+        exit 3
+        ;;
     esac
 done
 shift $(( OPTIND - 1 ));
@@ -68,11 +89,11 @@ export DIR="$1"
 #
 if [[ ! -e "$DIR" ]]; then
     echo "$0: FATAL: directory does not exist: $DIR" 1>&2
-    exit 3
+    exit 4
 fi
 if [[ ! -d "$DIR" ]]; then
     echo "$0: FATAL: not a directory: $DIR" 1>&2
-    exit 4
+    exit 5
 fi
 
 # determine if readlink --canonicalize-existing works
@@ -93,11 +114,11 @@ if [[ -n $HAS_CANONICALIZE_EXISTING ]]; then
     status="$?"
     if [[ "$status" -ne 0 ]]; then
 	echo "$0: FATAL: cannot canonicalize $DIR, error code: $status" 1>&2
-	exit 5
+	exit 6
     fi
     if [[ -z "$CANON_DIR" ]]; then
 	echo "$0: FATAL: DIR canonicalized $DIR to empty string" 1>&2
-	exit 6
+	exit 7
     fi
 else
     CANON_DIR=$(perl -MCwd -e 'print Cwd::realpath($ARGV[0]), "\n"' "$DIR")
@@ -106,26 +127,26 @@ if [[ -n "$VERBOSE" ]]; then
     echo "$0: Notice: CANON_DIR: $CANON_DIR" 1>&2
 fi
 
-# move to the directory
+# move to the parent directory
 #
 if [[ -n "$VERBOSE" ]]; then
-    echo "$0: Notice: cd $CANON_DIR" 1>&2
+   echo "$0: Notice: cd $CANON_DIR" 1>&2
 fi
-cd "$CANON_DIR"
-status="$?"
-if [[ "$status" -ne 0 ]]; then
-    echo "$0: FATAL: cannot cd $CANON_DIR, error code: $status" 1>&2
-    exit 7
+export CD_FAILED=""
+cd "$CANON_DIR" || CD_FAILED="true"
+if [[ -n $CD_FAILED ]]; then
+    echo "$0: ERROR: cd $CANON_DIR failed" 1>&2
+    exit 8
 fi
-if [[ -n "$VERBOSE" ]]; then
-    echo 1>&2
+if [[ -n $VERBOSE ]]; then
+    echo "$0: debug[3]: now in directory: $(/bin/pwd)" 1>&2
 fi
 
 # reject if not under git control
 #
 if ! git rev-parse --is-inside-work >/dev/null 2>&1; then
     echo "$0: FATAL: $DIR is not under git control" 1>&2
-    exit 8
+    exit 9
 fi
 
 # git status if verbose
@@ -147,14 +168,14 @@ if [[ -z "$NO_OP" ]]; then
 	status="$?"
 	if [[ "$status" -ne 0 ]]; then
 	    echo "$0: FATAL: git fetch error: $status" 1>&2
-	    exit 9
+	    exit 10
 	fi
     else
 	git fetch
 	status="$?"
 	if [[ "$status" -ne 0 ]]; then
 	    echo "$0: FATAL: git fetch error: $status" 1>&2
-	    exit 10
+	    exit 11
 	fi
     fi
 fi
@@ -173,14 +194,14 @@ if [[ -z "$NO_OP" ]]; then
 	status="$?"
 	if [[ "$status" -ne 0 ]]; then
 	    echo "$0: FATAL: git fetch --prune error: $status" 1>&2
-	    exit 11
+	    exit 12
 	fi
     else
 	git fetch --prune
 	status="$?"
 	if [[ "$status" -ne 0 ]]; then
 	    echo "$0: FATAL: git fetch --prune error: $status" 1>&2
-	    exit 12
+	    exit 13
 	fi
     fi
 fi
@@ -198,7 +219,7 @@ if [[ -n "$VERBOSE" ]]; then
     status="$?"
     if [[ "$status" -ne 0 ]]; then
 	echo "$0: FATAL: git add error: $status" 1>&2
-	exit 13
+	exit 14
     fi
 fi
 if [[ -n "$VERBOSE" ]]; then
@@ -215,7 +236,7 @@ if [[ -z "$NO_OP" ]]; then
     status="$?"
     if [[ "$status" -ne 0 ]]; then
 	echo "$0: FATAL: git commit error: $status" 1>&2
-	exit 14
+	exit 15
     fi
 fi
 if [[ -n "$VERBOSE" ]]; then
@@ -233,14 +254,14 @@ if [[ -z "$NO_OP" ]]; then
 	status="$?"
 	if [[ "$status" -ne 0 ]]; then
 	    echo "$0: FATAL: git commit error: $status" 1>&2
-	    exit 15
+	    exit 16
 	fi
     else
 	git push
 	status="$?"
 	if [[ "$status" -ne 0 ]]; then
 	    echo "$0: FATAL: git commit error: $status" 1>&2
-	    exit 16
+	    exit 17
 	fi
     fi
 fi
diff --git a/undergit b/undergit
--- a/undergit
+++ b/undergit
@@ -1,8 +1,8 @@
-#!/bin/bash -
+#!/usr/bin/env bash
 #
 # undergit - place a local directory under git control
 #
-# Copyright (c) 2016,2021 by Landon Curt Noll.  All Rights Reserved.
+# Copyright (c) 2016,2021,2025 by Landon Curt Noll.  All Rights Reserved.
 #
 # Permission to use, copy, modify, and distribute this software and
 # its documentation for any purpose and without fee is hereby granted,
@@ -28,31 +28,38 @@
 
 # setup
 #
+export VERSION="1.0.0 2025-03-17"
 export LOC_REPO_DIR="/usr/local/git"
-export USAGE="usage: $0 [-h] [-a] [-b] [-r locrepo] [-c] [-m commit] [-n] [-v] dir
-
-	-h          print this message and exit
-
-	-a	    do not commit (def: add all and commit)
-	-b	    do not add, do not commit (def: add all and commit)
-	-r locrepo  directory of the local git repo (def: $LOC_REPO_DIR)
-	-c	    do not clone to locrepo (def: bare clone to locrepo)
-	-m commit   use commit message when committing (def: 'under git control')
-
-        -n          do not create anything
-	-v          be verbose
-
-	dir	    directory to place under git control"
 export NO_COMMIT=""
 export NO_ADD=""
 export NO_CLONE=""
 export COMMIT_MSG="under git control"
 export VERBOSE=""
 export NO_OP=""
+NAME=$(basename "$0")
+export NAME
+#
+export USAGE="usage: $NAME
+
+    -h          print this message and exit
+    -v          be verbose
+    -V          print version string and exit
+
+    -n          do not create anything
+
+    -a          do not commit (def: add all and commit)
+    -b          do not add, do not commit (def: add all and commit)
+    -r locrepo  directory of the local git repo (def: $LOC_REPO_DIR)
+    -c          do not clone to locrepo (def: bare clone to locrepo)
+    -m commit   use commit message when committing (def: 'under git control')
+
+    dir         directory to place under git control
+
+$NAME version: $VERSION"
 
 # parse args
 #
-while getopts :habr:cm:nv flag; do
+while getopts :habr:cm:nvV flag; do
     case "$flag" in
     h) echo "$USAGE" 1>&2;
        exit 0
@@ -72,10 +79,24 @@ while getopts :habr:cm:nv flag; do
        ;;
     v) VERBOSE="-v"
        ;;
-    ?) echo "$0: FATAL: unknown or invalid -flag" 1>&2 ;
-       echo "$USAGE" 1>&2 ;
-       exit 1
+    V) echo "$VERSION"
+	exit 2
        ;;
+    \?) echo "$0: ERROR: invalid option: -$OPTARG" 1>&2
+        echo 1>&2
+        echo "$USAGE" 1>&2
+        exit 3
+        ;;
+    :) echo "$0: ERROR: option -$OPTARG requires an argument" 1>&2
+        echo 1>&2
+        echo "$USAGE" 1>&2
+        exit 3
+        ;;
+    *) echo "$0: ERROR: unexpected value from getopts: $flag" 1>&2
+        echo 1>&2
+        echo "$USAGE" 1>&2
+        exit 3
+        ;;
     esac
 done
 shift $(( OPTIND - 1 ));
@@ -90,19 +111,19 @@ export DIR="$1"
 #
 if [[ ! -e "$DIR" ]]; then
     echo "$0: FATAL: directory does not exist: $DIR" 1>&2
-    exit 3
+    exit 4
 fi
 if [[ ! -d "$DIR" ]]; then
     echo "$0: FATAL: not a directory: $DIR" 1>&2
-    exit 4
+    exit 5
 fi
 if [[ ! -e "$LOC_REPO_DIR" ]]; then
     echo "$0: FATAL: repo directory does not exist: $LOC_REPO_DIR" 1>&2
-    exit 5
+    exit 6
 fi
 if [[ ! -d "$LOC_REPO_DIR" ]]; then
     echo "$0: FATAL: repo is not a directory: $LOC_REPO_DIR" 1>&2
-    exit 6
+    exit 7
 fi
 
 # determine if readlink --canonicalize-existing works
@@ -123,11 +144,11 @@ if [[ -n $HAS_CANONICALIZE_EXISTING ]]; then
     status="$?"
     if [[ "$status" -ne 0 ]]; then
 	echo "$0: FATAL: cannot canonicalize $DIR, error code: $status" 1>&2
-	exit 7
+	exit 8
     fi
     if [[ -z "$CANON_DIR" ]]; then
 	echo "$0: FATAL: DIR canonicalized $DIR to empty string" 1>&2
-	exit 8
+	exit 9
     fi
 else
     CANON_DIR=$(perl -MCwd -e 'print Cwd::realpath($ARGV[0]), "\n"' "$DIR")
@@ -136,37 +157,42 @@ if [[ -n "$VERBOSE" ]]; then
     echo "$0: Notice: CANON_DIR: $CANON_DIR" 1>&2
 fi
 
-# move to the directory
+# move to the parent directory
 #
 if [[ -n "$VERBOSE" ]]; then
    echo "$0: Notice: cd $CANON_DIR" 1>&2
 fi
-cd "$CANON_DIR"
-status="$?"
-if [[ "$status" -ne 0 ]]; then
-    echo "$0: FATAL: cannot cd $CANON_DIR, error code: $status" 1>&2
-    exit 9
+export CD_FAILED=""
+cd "$CANON_DIR" || CD_FAILED="true"
+if [[ -n $CD_FAILED ]]; then
+    echo "$0: ERROR: cd $CANON_DIR failed" 1>&2
+    exit 10
+fi
+if [[ -n $VERBOSE ]]; then
+    echo "$0: debug[3]: now in directory: $(/bin/pwd)" 1>&2
 fi
 
 # reject if there is a similarly named git repo under $LOC_REPO_DIR
 #
-export NAME=$(basename "$CANON_DIR")
+NAME=$(basename "$CANON_DIR")
+export NAME
 if [[ -n "$VERBOSE" ]]; then
     echo "$0: Notice: NAME: $NAME" 1>&2
 fi
 if [[ -e "$LOC_REPO_DIR/$NAME" ]]; then
     echo "$0: FATAL: similarly named git repo found under: $LOC_REPO_DIR/$NAME" 1>&2
-    exit 10
+    exit 11
 fi
 if [[ -e "$LOC_REPO_DIR/$NAME.git" ]]; then
     echo "$0: FATAL: similarly named git repo found under: $LOC_REPO_DIR/$NAME.git" 1>&2
-    exit 11
+    exit 12
 fi
 
 # reject if already under git control or a sub-directory is under git control
 #
 if git rev-parse --is-inside-work >/dev/null 2>&1; then
-    export GIT_DIR_PATH=$(git rev-parse --git-dir 2>/dev/null)
+    GIT_DIR_PATH=$(git rev-parse --git-dir 2>/dev/null)
+    export GIT_DIR_PATH
     if [[ -z "$GIT_DIR_PATH" ]]; then
 	echo "$0: FATAL: $DIR is under git control, but .git is unknown" 1>&2
     else
@@ -181,7 +207,7 @@ if git rev-parse --is-inside-work >/dev/null 2>&1; then
 	    echo "$0: FATAL: $DIR is under git control: $NEW_GIT_DIR_PATH" 1>&2
 	fi
     fi
-    exit 12
+    exit 13
 fi
 
 # reject if sub-directory is under git control
@@ -198,7 +224,7 @@ if [[ -n "$SUB_GIT" ]]; then
     else
 	echo "$0: FATAL: a sub-directory of $DIR appears to be under git control: $NEW_SUB_GIT" 1>&2
     fi
-    exit 13
+    exit 14
 fi
 if [[ -n "$VERBOSE" ]]; then
     echo "$0: Notice: $DIR is not under git control" 1>&2
@@ -214,7 +240,7 @@ if [[ -z "$NO_OP" ]]; then
     status="$?"
     if [[ "$status" -ne 0 ]]; then
 	echo "$0: FATAL: git init error: $status" 1>&2
-	exit 14
+	exit 15
     fi
 fi
 
@@ -230,14 +256,14 @@ if [[ -z "$NO_ADD" ]]; then
 	    status="$?"
 	    if [[ "$status" -ne 0 ]]; then
 		echo "$0: FATAL: git add error: $status" 1>&2
-		exit 15
+		exit 16
 	    fi
 	else
 	    git add .
 	    status="$?"
 	    if [[ "$status" -ne 0 ]]; then
 		echo "$0: FATAL: git add error: $status" 1>&2
-		exit 16
+		exit 17
 	    fi
 	fi
     fi
@@ -266,7 +292,7 @@ if [[ -z "$NO_COMMIT" ]]; then
 	    status="$?"
 	    if [[ "$status" -ne 0 ]]; then
 		echo "$0: FATAL: git commit error: $status" 1>&2
-		exit 18
+		exit 19
 	    fi
 	fi
     fi
@@ -285,11 +311,14 @@ if [[ -z "$NO_CLONE" ]]; then
     if [[ -n "$VERBOSE" ]]; then
        echo "$0: Notice: cd $LOC_REPO_DIR" 1>&2
     fi
-    cd "$LOC_REPO_DIR"
-    status="$?"
-    if [[ "$status" -ne 0 ]]; then
-	echo "$0: FATAL: cannot cd $LOC_REPO_DIR, error code: $status" 1>&2
-	exit 19
+    export CD_FAILED=""
+    cd "$LOC_REPO_DIR" || CD_FAILED="true"
+    if [[ -n $CD_FAILED ]]; then
+	echo "$0: ERROR: cd $LOC_REPO_DIR failed" 1>&2
+	exit 20
+    fi
+    if [[ -n $VERBOSE ]]; then
+	echo "$0: debug[3]: now in directory: $(/bin/pwd)" 1>&2
     fi
 
     # determine if $LOC_REPO_DIR is same filesystem as $CANON_DIR
@@ -317,14 +346,14 @@ if [[ -z "$NO_CLONE" ]]; then
 	    status="$?"
 	    if [[ "$status" -ne 0 ]]; then
 		echo "$0: FATAL: git clone error: $status" 1>&2
-		exit 20
+		exit 21
 	    fi
 	else
 	    git clone --bare --local "$CLONE_ARG" "$CANON_DIR"
 	    status="$?"
 	    if [[ "$status" -ne 0 ]]; then
 		echo "$0: FATAL: git clone error: $status" 1>&2
-		exit 21
+		exit 22
 	    fi
 	fi
     fi
@@ -334,11 +363,14 @@ if [[ -z "$NO_CLONE" ]]; then
     if [[ -n "$VERBOSE" ]]; then
        echo "$0: Notice: cd $CANON_DIR" 1>&2
     fi
-    cd "$CANON_DIR"
-    status="$?"
-    if [[ "$status" -ne 0 ]]; then
-	echo "$0: FATAL: cannot cd $CANON_DIR, error code: $status" 1>&2
-	exit 22
+    export CD_FAILED=""
+    cd "$CANON_DIR" || CD_FAILED="true"
+    if [[ -n $CD_FAILED ]]; then
+	echo "$0: ERROR: cd $CANON_DIR failed" 1>&2
+	exit 23
+    fi
+    if [[ -n $VERBOSE ]]; then
+	echo "$0: debug[3]: now in directory: $(/bin/pwd)" 1>&2
     fi
 
     # set git remote
@@ -355,7 +387,7 @@ if [[ -z "$NO_CLONE" ]]; then
 	status="$?"
 	if [[ "$status" -ne 0 ]]; then
 	    echo "$0: FATAL: git remote error: $status" 1>&2
-	    exit 23
+	    exit 24
 	fi
     fi
 
@@ -373,7 +405,7 @@ if [[ -z "$NO_CLONE" ]]; then
 	status="$?"
 	if [[ "$status" -ne 0 ]]; then
 	    echo "$0: FATAL: git fetch error: $status" 1>&2
-	    exit 24
+	    exit 25
 	fi
     fi
 
@@ -391,7 +423,7 @@ if [[ -z "$NO_CLONE" ]]; then
 	status="$?"
 	if [[ "$status" -ne 0 ]]; then
 	    echo "$0: FATAL: git branch --set-upstream-to=origin/master error: $status" 1>&2
-	    exit 25
+	    exit 26
 	fi
     fi
 
@@ -403,7 +435,7 @@ if [[ -z "$NO_CLONE" ]]; then
 	status="$?"
 	if [[ "$status" -ne 0 ]]; then
 	    echo "$0: FATAL: git remote error: $status" 1>&2
-	    exit 26
+	    exit 27
 	fi
     fi
 else
