fix how remote get-url is processed, sequence exit codes

diff --git a/ghreplace b/ghreplace
--- a/ghreplace
+++ b/ghreplace
@@ -162,15 +162,11 @@ fi
 if [[ -n $V_FLAG ]]; then
     echo "$0: notice: git remote get-url origin"
 fi
+export GITHUB_REPO_REMOTE="$GITHUB_REPO_BASE/$NAME"
+export GITHUB_REPO_REMOTE_GIT="$GITHUB_REPO_REMOTE.git"
 GIT_REMOTE_ORIGIN=$(git remote get-url origin)
-if [[ $GIT_REMOTE_ORIGIN =~ \.git$ ]]; then
-    GIT_LOCAL_REPO_PATH="$LOCAL_GIT_TREE/$NAME.git"
-else
-    GIT_LOCAL_REPO_PATH="$LOCAL_GIT_TREE/$NAME"
-fi
-export GIT_LOCAL_REPO_PATH
-if [[ $GIT_REMOTE_ORIGIN != "$GIT_LOCAL_REPO_PATH" ]]; then
-    echo "$0: ERROR: git remote origin is $GIT_REMOTE_ORIGIN != $GIT_LOCAL_REPO_PATH" 1>&2
+if [[ $GIT_REMOTE_ORIGIN != "$GITHUB_REPO_REMOTE" && $GIT_REMOTE_ORIGIN != "$GITHUB_REPO_REMOTE_GIT" ]]; then
+    echo "$0: ERROR: git remote new-origin is neither $GITHUB_REPO_REMOTE nor $GITHUB_REPO_REMOTE_GIT" 1>&2
     exit 13
 fi
 
@@ -230,21 +226,20 @@ fi
 
 # require that an non-empty GitHub repo exists now
 #
-export GITHUB_REPO_REMOTE="$GITHUB_REPO_BASE/$NAME.git"
 if [[ -n $V_FLAG ]]; then
-    echo "$0: notice: git ls-remote $GITHUB_REPO_REMOTE 2>/dev/null"
+    echo "$0: notice: git ls-remote $GITHUB_REPO_REMOTE_GIT 2>/dev/null"
 fi
-GITHUB_LS_REMOTE=$(git ls-remote "$GITHUB_REPO_REMOTE" 2>/dev/null)
+GITHUB_LS_REMOTE=$(git ls-remote "$GITHUB_REPO_REMOTE_GIT" 2>/dev/null)
 status="$?"
 if [[ $status -ne 0 ]]; then
-    echo "$0: ERROR: cannot find GitHub repo: $GITHUB_REPO_REMOTE" 1>&2
+    echo "$0: ERROR: cannot find GitHub repo: $GITHUB_REPO_REMOTE_GIT" 1>&2
     exit 20
 fi
 if [[ -z $GITHUB_LS_REMOTE ]]; then
-    echo "$0: ERROR: git ls-remote $GITHUB_REPO_REMOTE is empty" 1>&2
+    echo "$0: ERROR: git ls-remote $GITHUB_REPO_REMOTE_GIT is empty" 1>&2
     exit 21
 elif [[ -n $V_FLAG ]]; then
-    echo "$0: notice: GitHub is: $GITHUB_REPO_REMOTE"
+    echo "$0: notice: GitHub is: $GITHUB_REPO_REMOTE_GIT"
 fi
 
 # move to top of source above where name is found
@@ -318,13 +313,13 @@ fi
 # clone the GitHub repo
 #
 if [[ -n $V_FLAG ]]; then
-    echo "$0: notice: git clone $GITHUB_REPO_REMOTE"
+    echo "$0: notice: git clone $GITHUB_REPO_REMOTE_GIT"
 fi
 if [[ -z $N_FLAG ]]; then
-    git clone "$GITHUB_REPO_REMOTE"
+    git clone "$GITHUB_REPO_REMOTE_GIT"
     status="$?"
     if [[ $status -ne 0 ]]; then
-	echo "$0: ERROR: git clone $GITHUB_REPO_REMOTE failed, exit code: $status" 1>&2
+	echo "$0: ERROR: git clone $GITHUB_REPO_REMOTE_GIT failed, exit code: $status" 1>&2
 	exit 28
     fi
 
diff --git a/git2gh b/git2gh
--- a/git2gh
+++ b/git2gh
@@ -1,4 +1,4 @@
-#!/usr/bin/env bash
+_GIT#!/usr/bin/env bash
 #
 # git2gh - convert a local git repo into a GitHub repo
 #
@@ -163,14 +163,10 @@ fi
 if [[ -n $V_FLAG ]]; then
     echo "$0: notice: git remote get-url origin"
 fi
+export GIT_LOCAL_REPO_PATH="$LOCAL_GIT_TREE/$NAME"
+export GIT_LOCAL_REPO_PATH_GIT="$GIT_LOCAL_REPO_PATH.git"
 GIT_REMOTE_ORIGIN=$(git remote get-url origin)
-if [[ $GIT_REMOTE_ORIGIN =~ \.git$ ]]; then
-    GIT_LOCAL_REPO_PATH="$LOCAL_GIT_TREE/$NAME.git"
-else
-    GIT_LOCAL_REPO_PATH="$LOCAL_GIT_TREE/$NAME"
-fi
-export GIT_LOCAL_REPO_PATH
-if [[ $GIT_REMOTE_ORIGIN != "$GIT_LOCAL_REPO_PATH" ]]; then
+if [[ $GIT_REMOTE_ORIGIN != "$GIT_LOCAL_REPO_PATH" && $GIT_REMOTE_ORIGIN != "$GIT_LOCAL_REPO_PATH_GIT" ]]; then
     echo "$0: ERROR: git remote origin is $GIT_REMOTE_ORIGIN != $GIT_LOCAL_REPO_PATH" 1>&2
     exit 13
 fi
@@ -266,11 +262,12 @@ fi
 
 # see if a GitHub repo exists
 #
-GITHUB_REPO_REMOTE="$GITHUB_REPO_BASE/$NAME"
+export GITHUB_REPO_REMOTE="$GITHUB_REPO_BASE/$NAME"
+export GITHUB_REPO_REMOTE_GIT="$GITHUB_REPO_REMOTE.git"
 if [[ -n $V_FLAG ]]; then
-    echo "$0: notice: git ls-remote $GITHUB_REPO_REMOTE 2>/dev/null"
+    echo "$0: notice: git ls-remote $GITHUB_REPO_REMOTE_GIT 2>/dev/null"
 fi
-GITHUB_LS_REMOTE=$(git ls-remote "$GITHUB_REPO_REMOTE" 2>/dev/null)
+GITHUB_LS_REMOTE=$(git ls-remote "$GITHUB_REPO_REMOTE_GIT" 2>/dev/null)
 status="$?"
 if [[ $status -eq 0 ]]; then
     GITHUB_REPO_EXISTS="true"
@@ -312,38 +309,37 @@ if [[ -z $GITHUB_REPO_EXISTS ]]; then
     read -r -p "Press return when done, or ^C to abort: "
     echo
 elif [[ -n $V_FLAG ]]; then
-    echo "$0: notice: GitHub repo exists: $GITHUB_REPO_REMOTE"
+    echo "$0: notice: GitHub repo exists: $GITHUB_REPO_REMOTE_GIT"
 fi
 
 # require that an empty GitHub repo exists now
 #
-export GITHUB_REPO_REMOTE="$GITHUB_REPO_BASE/$NAME.git"
 if [[ -n $V_FLAG ]]; then
-    echo "$0: notice: git ls-remote $GITHUB_REPO_REMOTE 2>/dev/null"
+    echo "$0: notice: git ls-remote $GITHUB_REPO_REMOTE_GIT 2>/dev/null"
 fi
-GITHUB_LS_REMOTE=$(git ls-remote "$GITHUB_REPO_REMOTE" 2>/dev/null)
+GITHUB_LS_REMOTE=$(git ls-remote "$GITHUB_REPO_REMOTE_GIT" 2>/dev/null)
 status="$?"
 if [[ $status -ne 0 ]]; then
-    echo "$0: ERROR: cannot find GitHub repo: $GITHUB_REPO_REMOTE" 1>&2
+    echo "$0: ERROR: cannot find GitHub repo: $GITHUB_REPO_REMOTE_GIT" 1>&2
     exit 24
 fi
 if [[ -n $GITHUB_LS_REMOTE ]]; then
-    echo "$0: ERROR: git ls-remote $GITHUB_REPO_REMOTE was NOT empty" 1>&2
+    echo "$0: ERROR: git ls-remote $GITHUB_REPO_REMOTE_GIT was NOT empty" 1>&2
     exit 25
 elif [[ -n $V_FLAG ]]; then
-    echo "$0: notice: GitHub is: $GITHUB_REPO_REMOTE"
+    echo "$0: notice: GitHub is: $GITHUB_REPO_REMOTE_GIT"
 fi
 
 # add a new repo as a new remote origin
 #
 if [[ -n $V_FLAG ]]; then
-    echo "$0: notice: git remote add new-origin $GITHUB_REPO_REMOTE"
+    echo "$0: notice: git remote add new-origin $GITHUB_REPO_REMOTE_GIT"
 fi
 if [[ -z $N_FLAG ]]; then
-    git remote add new-origin "$GITHUB_REPO_REMOTE"
+    git remote add new-origin "$GITHUB_REPO_REMOTE_GIT"
     status="$?"
     if [[ $status -ne 0 ]]; then
-	echo "$0: ERROR: git remote add new-origin $GITHUB_REPO_REMOTE failed, exit code: $status" 1>&2
+	echo "$0: ERROR: git remote add new-origin $GITHUB_REPO_REMOTE_GIT failed, exit code: $status" 1>&2
 	exit 26
     fi
 
@@ -353,9 +349,13 @@ if [[ -z $N_FLAG ]]; then
 	echo "$0: notice: git remote get-url new-origin"
     fi
     GIT_REMOTE_ORIGIN=$(git remote get-url new-origin 2>/dev/null)
-    if [[ $GIT_REMOTE_ORIGIN != "$GITHUB_REPO_REMOTE" ]]; then
-	echo "$0: ERROR: git remote new-origin not found or is not: $GITHUB_REPO_REMOTE" 1>&2
+    if [[ -z $GIT_REMOTE_ORIGIN ]]; then
+	echo "$0: ERROR: git remote new-origin is emoty" 1>&2
 	exit 27
+    fi
+    if [[ $GIT_REMOTE_ORIGIN != "$GITHUB_REPO_REMOTE" && $GIT_REMOTE_ORIGIN != "$GITHUB_REPO_REMOTE_GIT" ]]; then
+	echo "$0: ERROR: git remote new-origin is neither $GITHUB_REPO_REMOTE nor $GITHUB_REPO_REMOTE_GIT" 1>&2
+	exit 28
     fi
 fi
 
@@ -369,7 +369,7 @@ if [[ -z $N_FLAG ]]; then
     status="$?"
     if [[ $status -ne 0 ]]; then
 	echo "$0: ERROR: git push --all new-origin failed, exit code: $status" 1>&2
-	exit 28
+	exit 29
     fi
 fi
 
@@ -383,7 +383,7 @@ if [[ -z $N_FLAG ]]; then
     status="$?"
     if [[ $status -ne 0 ]]; then
 	echo "$0: ERROR: git push --tags new-origin failed, exit code: $status" 1>&2
-	exit 29
+	exit 30
     fi
 fi
 
@@ -397,7 +397,7 @@ if [[ -z $N_FLAG ]]; then
     status="$?"
     if [[ $status -ne 0 ]]; then
 	echo "$0: ERROR: git remote rm origin failed, exit code: $status" 1>&2
-	exit 30
+	exit 31
     fi
 fi
 
@@ -411,7 +411,7 @@ if [[ -z $N_FLAG ]]; then
     status="$?"
     if [[ $status -ne 0 ]]; then
 	echo "$0: ERROR: git remote rename new-origin origin failed, exit code: $status" 1>&2
-	exit 31
+	exit 32
     fi
 
     # verify that the origin is now on GitHub
@@ -423,19 +423,23 @@ if [[ -z $N_FLAG ]]; then
     status="$?"
     if [[ $status -ne 0 ]]; then
 	echo "$0: ERROR: git remote failed, exit code: $status" 1>&2
-	exit 32
+	exit 33
     fi
     if [[ $GIT_REMOTE != "origin" ]]; then
 	echo "$0: ERROR: git remote is not origin: $GIT_REMOTE" 1>&2
-	exit 33
+	exit 34
     fi
     if [[ -n $V_FLAG ]]; then
 	echo "$0: notice: git remote get-url origin"
     fi
     GIT_REMOTE_ORIGIN=$(git remote get-url origin)
-    if [[ $GIT_REMOTE_ORIGIN != "$GITHUB_REPO_REMOTE" ]]; then
-	echo "$0: ERROR: git remote origin is not $GITHUB_REPO_REMOTE: $GIT_REMOTE_ORIGIN" 1>&2
-	exit 34
+    if [[ -z $GIT_REMOTE_ORIGIN ]]; then
+	echo "$0: ERROR: git remote new-origin is emoty" 1>&2
+	exit 35
+    fi
+    if [[ $GIT_REMOTE_ORIGIN != "$GITHUB_REPO_REMOTE" && $GIT_REMOTE_ORIGIN != "$GITHUB_REPO_REMOTE_GIT" ]]; then
+	echo "$0: ERROR: git remote new-origin is neither $GITHUB_REPO_REMOTE nor $GITHUB_REPO_REMOTE_GIT" 1>&2
+	exit 36
     fi
 
     # verify we are on the master branch
@@ -447,11 +451,11 @@ if [[ -z $N_FLAG ]]; then
     status="$?"
     if [[ $status -ne 0 ]]; then
 	echo "$0: ERROR: git branch --show-current failed, exit code: $status" 1>&2
-	exit 35
+	exit 37
     fi
     if [[ $CURRENT_BRANCH != master ]]; then
 	echo "$0: ERROR: git branch is not master: $CURRENT_BRANCH" 1>&2
-	exit 36
+	exit 38
     fi
 
     # set branch master upstream branch
@@ -464,7 +468,7 @@ if [[ -z $N_FLAG ]]; then
 	status="$?"
 	if [[ $status -ne 0 ]]; then
 	    echo "$0: ERROR: git branch --set-upstream-to=origin/master failed, exit code: $status" 1>&2
-	    exit 37
+	    exit 39
 	fi
     fi
 fi
@@ -488,14 +492,14 @@ if [[ -z $N_FLAG ]]; then
     status="$?"
     if [[ $status -ne 0 ]]; then
 	echo "$0: ERROR: rm -rf $LOCAL_GIT_REPO_DIR failed, exit code: $status" 1>&2
-	exit 38
+	exit 40
     fi
 
     # verify local git repo is now gone
     #
     if [[ -e $LOCAL_GIT_REPO_DIR ]]; then
 	echo "$0: ERROR: local git repo still exists: $LOCAL_GIT_REPO_DIR" 1>&2
-	exit 39
+	exit 41
     elif [[ -n $V_FLAG ]]; then
 	echo "$0: notice: local git repo removed: $LOCAL_GIT_REPO_DIR"
     fi
