add ghreplace, update comments in git2gh

diff --git a/ghreplace b/ghreplace
--- a/ghreplace
+++ b/ghreplace
@@ -1,8 +1,8 @@
 #!/usr/bin/env bash
 #
-# git2gh - convert a local git repo into a GitHub repo
+# ghreplace - replace local git repo with GitHub repo
 #
-# Convert a local repo to a GitHub repo with all branches, history and tags.
+# Replace a local src tree with GitHub repo content, remove local git repo
 #
 # Copyright (c) 2023 by Landon Curt Noll.  All Rights Reserved.
 #
@@ -37,7 +37,6 @@ if [[ -d /usr/global/git ]]; then
 else
     LOCAL_GIT_TREE="/usr/local/git"
 fi
-export LOCAL_GIT_TREE
 export GITHUB_REPO_BASE="git@github.com:$GITHUB_USER"
 export GITHUB_USER_URL="https://github.com/$GITHUB_USER"
 export N_FLAG=
@@ -224,93 +223,7 @@ if [[ -n $IS_CLEAN ]]; then
     exit 1
 fi
 
-# set branch master upstream branch
-#
-if [[ -n $V_FLAG ]]; then
-    echo "$0: notice: git push --set-upstream origin master"
-fi
-if [[ -z $N_FLAG ]]; then
-    git push --set-upstream origin master
-    status="$?"
-    if [[ $status -ne 0 ]]; then
-	echo "$0: ERROR: git push --set-upstream origin master failed, exit code: $status" 1>&2
-	exit 1
-    fi
-fi
-
-# verify the Makefile exists
-#
-MAKEFILE="$DIR/Makefile"
-if [[ ! -f $MAKEFILE ]]; then
-    echo "$0: ERROR: missing Makefile: $MAKEFILE" 1>&2
-    exit 1
-fi
-
-# verify proper #! line in Makefile
-#
-if [[ -n $V_FLAG ]]; then
-    echo "$0: notice: head -1 $MAKEFILE"
-fi
-HASHBANG=$(head -1 "$MAKEFILE")
-if [[ $HASHBANG != "#!/usr/bin/env make" ]]; then
-    echo "$0: ERROR: improper #! line in Makefile: $MAKEFILE" 1>&2
-    echo "$0: ERROR: found: $HASHBANG" 1>&2
-    echo "$0: ERROR: expected: #!/usr/bin/env make" 1>&2
-    exit 1
-fi
-
-# see if a GitHub repo exists
-#
-GITHUB_REPO_REMOTE="$GITHUB_REPO_BASE/$NAME"
-if [[ -n $V_FLAG ]]; then
-    echo "$0: notice: git ls-remote $GITHUB_REPO_REMOTE 2>/dev/null"
-fi
-GITHUB_LS_REMOTE=$(git ls-remote "$GITHUB_REPO_REMOTE" 2>/dev/null)
-status="$?"
-if [[ $status -eq 0 ]]; then
-    GITHUB_REPO_EXISTS="true"
-else
-    GITHUB_REPO_EXISTS=
-fi
-export GITHUB_REPO_EXISTS
-
-# look for summary comment line in Makefile
-#
-if [[ -n $V_FLAG ]]; then
-    echo "$0: notice: grep -E  '^# [^-][^-]* -' $MAKEFILE | head -1"
-fi
-SUMMARY=$(grep -E  '^# [^-][^-]* -' "$MAKEFILE" | head -1)
-if [[ -z $SUMMARY ]]; then
-    echo "$0: ERROR: did not find summary comment line in Makefile: $MAKEFILE" 1>&2
-    exit 1
-fi
-if [[ -n $V_FLAG ]]; then
-    echo "$0: notice: summary comment line: $SUMMARY"
-fi
-
-# if we do not key have a GitHub repo, ask that it be created
-#
-if [[ -z $GITHUB_REPO_EXISTS ]]; then
-    echo "$0: notice: GitHub repo does not yet exist"
-    echo "$0: notice: Create a private GitHub empty via: $GITHUB_USER_URL"
-    echo "$0: notice: Press the + in the upper right corner and select: 'New repository'"
-    echo
-    echo "$0: notice: Enter Repository name"
-    echo "$0: notice: Enter Description"
-    echo
-    echo "$0: notice: Enter data based on: $SUMMARY"
-    echo
-    echo "$0: notice: Select (*) Private"
-    echo
-    echo "$0: notice: click ((Create repository)) at the bottom"
-    echo
-    read -r -p "Press return when done, or ^C to abort: "
-    echo
-elif [[ -n $V_FLAG ]]; then
-    echo "$0: notice: GitHub repo exists: $GITHUB_REPO_REMOTE"
-fi
-
-# require that an empty GitHub repo exists now
+# require that an non-empty GitHub repo exists now
 #
 export GITHUB_REPO_REMOTE="$GITHUB_REPO_BASE/$NAME.git"
 if [[ -n $V_FLAG ]]; then
@@ -322,116 +235,24 @@ if [[ $status -ne 0 ]]; then
     echo "$0: ERROR: cannot find GitHub repo: $GITHUB_REPO_REMOTE" 1>&2
     exit 1
 fi
-if [[ -n $GITHUB_LS_REMOTE ]]; then
-    echo "$0: ERROR: git ls-remote $GITHUB_REPO_REMOTE was NOT empty" 1>&2
+if [[ -z $GITHUB_LS_REMOTE ]]; then
+    echo "$0: ERROR: git ls-remote $GITHUB_REPO_REMOTE is empty" 1>&2
     exit 1
 elif [[ -n $V_FLAG ]]; then
     echo "$0: notice: GitHub is: $GITHUB_REPO_REMOTE"
 fi
 
-# add a new repo as a new remote origin
+# move to top of source above where name is found
 #
-if [[ -n $V_FLAG ]]; then
-    echo "$0: notice: git remote add new-origin $GITHUB_REPO_REMOTE"
+status=0
+cd "$LOCAL_SRC_TREE" || status="$?"
+if [[ $status -ne 0 ]]; then
+    echo "$0: ERROR: cd $LOCAL_SRC_TREE failed, exit code: $status" 1>&2
+    exit 1
 fi
-if [[ -z $N_FLAG ]]; then
-    git remote add new-origin "$GITHUB_REPO_REMOTE"
-    status="$?"
-    if [[ $status -ne 0 ]]; then
-	echo "$0: ERROR: git remote add new-origin $GITHUB_REPO_REMOTE failed, exit code: $status" 1>&2
-	exit 1
-    fi
-
-    # verify that the new remote origin exists and has the correct URL
-    #
-    if [[ -n $V_FLAG ]]; then
-	echo "$0: notice: git remote get-url new-origin"
-    fi
-    GIT_REMOTE_ORIGIN=$(git remote get-url new-origin 2>/dev/null)
-    if [[ $GIT_REMOTE_ORIGIN != "$GITHUB_REPO_REMOTE" ]]; then
-	echo "$0: ERROR: git remote new-origin not found or is not: $GITHUB_REPO_REMOTE" 1>&2
-	exit 1
-    fi
-fi
-
-# push all local branches to the "new repo"
-#
-if [[ -n $V_FLAG ]]; then
-    echo "$0: notice: git push --all new-origin"
-fi
-if [[ -z $N_FLAG ]]; then
-    git push --all new-origin
-    status="$?"
-    if [[ $status -ne 0 ]]; then
-	echo "$0: ERROR: git push --all new-origin failed, exit code: $status" 1>&2
-	exit 1
-    fi
-fi
-
-# push all tags to the "new repo"
-#
-if [[ -n $V_FLAG ]]; then
-    echo "$0: notice: git push --tags new-origin"
-fi
-if [[ -z $N_FLAG ]]; then
-    git push --tags new-origin
-    status="$?"
-    if [[ $status -ne 0 ]]; then
-	echo "$0: ERROR: git push --tags new-origin failed, exit code: $status" 1>&2
-	exit 1
-    fi
-fi
-
-# remote "old repo" remote
-#
-if [[ -n $V_FLAG ]]; then
-    echo "$0: notice: git remote rm origin"
-fi
-if [[ -z $N_FLAG ]]; then
-    git remote rm origin
-    status="$?"
-    if [[ $status -ne 0 ]]; then
-	echo "$0: ERROR: git remote rm origin failed, exit code: $status" 1>&2
-	exit 1
-    fi
-fi
-
-# rename "new repo" remote into just origin
-#
-if [[ -n $V_FLAG ]]; then
-    echo "$0: notice: git remote rename new-origin origin"
-fi
-if [[ -z $N_FLAG ]]; then
-    git remote rename new-origin origin
-    status="$?"
-    if [[ $status -ne 0 ]]; then
-	echo "$0: ERROR: git remote rename new-origin origin failed, exit code: $status" 1>&2
-	exit 1
-    fi
-
-    # verify that the origin is now on GitHub
-    #
-    if [[ -n $V_FLAG ]]; then
-	echo "$0: notice: git remote"
-    fi
-    GIT_REMOTE=$(git remote)
-    status="$?"
-    if [[ $status -ne 0 ]]; then
-	echo "$0: ERROR: git remote failed, exit code: $status" 1>&2
-	exit 1
-    fi
-    if [[ $GIT_REMOTE != "origin" ]]; then
-	echo "$0: ERROR: git remote is not origin: $GIT_REMOTE" 1>&2
-	exit 1
-    fi
-    if [[ -n $V_FLAG ]]; then
-	echo "$0: notice: git remote get-url origin"
-    fi
-    GIT_REMOTE_ORIGIN=$(git remote get-url origin)
-    if [[ $GIT_REMOTE_ORIGIN != "$GITHUB_REPO_REMOTE" ]]; then
-	echo "$0: ERROR: git remote origin is not $GITHUB_REPO_REMOTE: $GIT_REMOTE_ORIGIN" 1>&2
-	exit 1
-    fi
+if [[ ! -d $NAME ]]; then
+    echo "$0: ERROR: $NAME is not a directory under $LOCAL_SRC_TREE" 1>&2
+    exit 1
 fi
 
 # verify that GitHub has updated data
@@ -466,8 +287,56 @@ if [[ -z $N_FLAG ]]; then
     fi
 fi
 
+# remove the local src tree
+#
+if [[ -n $V_FLAG ]]; then
+    echo "$0: notice: rm -rf $DIR"
+fi
+if [[ -z $N_FLAG ]]; then
+    rm -rf "$DIR"
+    status="$?"
+    if [[ $status -ne 0 ]]; then
+	echo "$0: ERROR: rm -rf $DIR failed, exit code: $status" 1>&2
+	exit 1
+    fi
+
+    # verify local git repo is now gone
+    #
+    if [[ -e $DIR ]]; then
+	echo "$0: ERROR: local src tree still exists: $DIR" 1>&2
+	exit 1
+    elif [[ -n $V_FLAG ]]; then
+	echo "$0: notice: local src tree removed: $DIR"
+    fi
+fi
+
+# clone the GitHub repo
+#
+if [[ -n $V_FLAG ]]; then
+    echo "$0: notice: git clone $GITHUB_REPO_REMOTE"
+fi
+if [[ -z $N_FLAG ]]; then
+    git clone "$GITHUB_REPO_REMOTE"
+    status="$?"
+    if [[ $status -ne 0 ]]; then
+	echo "$0: ERROR: git clone $GITHUB_REPO_REMOTE failed, exit code: $status" 1>&2
+	exit 1
+    fi
+
+    # verify local git repo exists
+    #
+    if [[ ! -d $LOCAL_GIT_REPO_DIR ]]; then
+	echo "$0: ERROR: local git repo is missing: $LOCAL_GIT_REPO_DIR" 1>&2
+	exit 1
+    fi
+    if [[ ! -d $LOCAL_GIT_REPO_DIR/.git ]]; then
+	echo "$0: ERROR: local git repo .git tree is missing: $LOCAL_GIT_REPO_DIR/.git" 1>&2
+	exit 1
+    fi
+fi
+
 # All Done!!! -- Jessica Noll, Age 2
 #
 echo
-echo "$0: notice: $DIR now lives in GitHub at: $GITHUB_REPO_URL"
+echo "$0: notice: cd $DIR && make clobber all && sudo make install"
 exit 0
