added git fetch --prune stage

diff --git a/syncgit b/syncgit
--- a/syncgit
+++ b/syncgit
@@ -147,15 +147,41 @@ if [[ -z "$NO_OP" ]]; then
 	git fetch -v
 	status="$?"
 	if [[ "$status" -ne 0 ]]; then
-	    echo "$0: FATAL: git init error: $status" 1>&2
+	    echo "$0: FATAL: git fetch error: $status" 1>&2
 	    exit 9
 	fi
     else
 	git fetch
 	status="$?"
 	if [[ "$status" -ne 0 ]]; then
-	    echo "$0: FATAL: git init error: $status" 1>&2
+	    echo "$0: FATAL: git fetch error: $status" 1>&2
 	    exit 10
+	fi
+    fi
+fi
+if [[ -n "$VERBOSE" ]]; then
+    echo 1>&2
+fi
+
+# git fetch and prune
+#
+if [[ -n "$VERBOSE" ]]; then
+    echo "$0: Notice: git fetch $VERBOSE" 1>&2
+fi
+if [[ -z "$NO_OP" ]]; then
+    if [[ -n "$VERBOSE" ]]; then
+	git fetch -v --prune
+	status="$?"
+	if [[ "$status" -ne 0 ]]; then
+	    echo "$0: FATAL: git fetch --prune error: $status" 1>&2
+	    exit 11
+	fi
+    else
+	git fetch --prune
+	status="$?"
+	if [[ "$status" -ne 0 ]]; then
+	    echo "$0: FATAL: git fetch --prune error: $status" 1>&2
+	    exit 12
 	fi
     fi
 fi
@@ -173,7 +199,7 @@ if [[ -n "$VERBOSE" ]]; then
     status="$?"
     if [[ "$status" -ne 0 ]]; then
 	echo "$0: FATAL: git add error: $status" 1>&2
-	exit 11
+	exit 13
     fi
 fi
 if [[ -n "$VERBOSE" ]]; then
@@ -190,7 +216,7 @@ if [[ -z "$NO_OP" ]]; then
     status="$?"
     if [[ "$status" -ne 0 ]]; then
 	echo "$0: FATAL: git commit error: $status" 1>&2
-	exit 12
+	exit 14
     fi
 fi
 if [[ -n "$VERBOSE" ]]; then
@@ -208,14 +234,14 @@ if [[ -z "$NO_OP" ]]; then
 	status="$?"
 	if [[ "$status" -ne 0 ]]; then
 	    echo "$0: FATAL: git commit error: $status" 1>&2
-	    exit 13
+	    exit 15
 	fi
     else
 	git push
 	status="$?"
 	if [[ "$status" -ne 0 ]]; then
 	    echo "$0: FATAL: git commit error: $status" 1>&2
-	    exit 14
+	    exit 16
 	fi
     fi
 fi
