only git show with -v

diff --git a/syncgit b/syncgit
--- a/syncgit
+++ b/syncgit
@@ -154,12 +154,12 @@ fi
 unset LESS
 if [[ -n "$VERBOSE" ]]; then
     echo "$0: Notice: git show --pretty=format: --name-only HEAD..origin/master" 1>&2
-fi
-git show --pretty=format: --name-only HEAD..origin/master
-status="$?"
-if [[ "$status" -ne 0 ]]; then
-    echo "$0: FATAL: git add error: $status" 1>&2
-    exit 11
+    git show --pretty=format: --name-only HEAD..origin/master
+    status="$?"
+    if [[ "$status" -ne 0 ]]; then
+	echo "$0: FATAL: git add error: $status" 1>&2
+	exit 11
+    fi
 fi
 
 # git rebase
